"""
AI Shield - Configuration and i18n
"""

# Default AI service ports
DEFAULT_PORTS = {
    11434: "Ollama",
    8000: "vLLM",
    8080: "llama.cpp / LocalAI",
    1234: "LM Studio",
    3000: "Open WebUI",
    7860: "Text-Generation-WebUI",
    5000: "LocalAI (alt)",
    9090: "vLLM (alt)",
}

# Risk severity levels
SEVERITY = {
    "critical": {"weight": 10, "color": "#dc2626"},
    "high":     {"weight": 8,  "color": "#ea580c"},
    "medium":   {"weight": 5,  "color": "#d97706"},
    "low":      {"weight": 2,  "color": "#65a30d"},
    "info":     {"weight": 0,  "color": "#2563eb"},
}

# i18n translations
I18N = {
    "zh": {
        "app_name": "AI Shield",
        "app_desc": "本地 AI 安全扫描工具",
        "scan": "扫描",
        "new_scan": "新建扫描",
        "target": "目标地址",
        "target_placeholder": "输入 IP 或域名（如 127.0.0.1 或 192.168.1.0/24）",
        "port_range": "端口范围",
        "default_ports": "默认 AI 端口",
        "all_ports": "全端口（1-65535）",
        "custom_ports": "自定义端口",
        "check_items": "检查项",
        "network_exposure": "网络暴露",
        "network_exposure_desc": "检查 API 是否绑定 0.0.0.0，外部是否可达",
        "auth_missing": "认证缺失",
        "auth_missing_desc": "检查是否缺少 API Key 或身份认证",
        "cve_check": "已知漏洞",
        "cve_check_desc": "匹配已知 CVE（Ollama/vLLM 等）",
        "prompt_injection": "Prompt 注入",
        "prompt_injection_desc": "测试系统提示词是否可被提取",
        "data_leak": "数据泄露",
        "data_leak_desc": "测试模型是否泄露训练数据",
        "file_access": "文件读取",
        "file_access_desc": "测试是否可通过 API 读取本地文件",
        "resource_abuse": "资源滥用",
        "resource_abuse_desc": "检查是否缺少速率限制",
        "cors_check": "CORS 配置",
        "cors_check_desc": "检查跨域策略是否过于宽松",
        "model_access": "模型访问",
        "model_access_desc": "检查未授权用户是否可列出/下载模型",
        "start_scan": "开始扫描",
        "scanning": "扫描中...",
        "scan_complete": "扫描完成",
        "risk_score": "风险评分",
        "findings": "发现问题",
        "critical": "严重",
        "high": "高危",
        "medium": "中危",
        "low": "低危",
        "info": "信息",
        "no_issues": "未发现安全问题",
        "recommendation": "修复建议",
        "evidence": "证据",
        "export_html": "导出 HTML 报告",
        "export_pdf": "导出 PDF",
        "history": "历史扫描",
        "settings": "设置",
        "language": "语言",
        "back": "返回",
        "close": "关闭",
        "port": "端口",
        "service": "服务",
        "version": "版本",
        "status": "状态",
        "open": "开放",
        "closed": "关闭",
        "filtered": "过滤",
        "details": "详情",
        "summary": "概览",
        "grade": "安全评级",
        "scan_time": "扫描耗时",
        "target_info": "目标信息",
        "total_ports": "扫描端口数",
        "open_ports": "开放端口数",
        "ai_services": "AI 服务数",
    },
    "en": {
        "app_name": "AI Shield",
        "app_desc": "Local AI Security Scanner",
        "scan": "Scan",
        "new_scan": "New Scan",
        "target": "Target",
        "target_placeholder": "Enter IP or domain (e.g. 127.0.0.1 or 192.168.1.0/24)",
        "port_range": "Port Range",
        "default_ports": "Default AI Ports",
        "all_ports": "All Ports (1-65535)",
        "custom_ports": "Custom Ports",
        "check_items": "Check Items",
        "network_exposure": "Network Exposure",
        "network_exposure_desc": "Check if API binds to 0.0.0.0 and is externally accessible",
        "auth_missing": "Missing Authentication",
        "auth_missing_desc": "Check if API Key or authentication is missing",
        "cve_check": "Known CVEs",
        "cve_check_desc": "Match known CVEs (Ollama/vLLM etc.)",
        "prompt_injection": "Prompt Injection",
        "prompt_injection_desc": "Test if system prompt can be extracted",
        "data_leak": "Data Leakage",
        "data_leak_desc": "Test if model leaks training data",
        "file_access": "File Read",
        "file_access_desc": "Test if local files can be read via API",
        "resource_abuse": "Resource Abuse",
        "resource_abuse_desc": "Check if rate limiting is missing",
        "cors_check": "CORS Configuration",
        "cors_check_desc": "Check if CORS policy is too permissive",
        "model_access": "Model Access",
        "model_access_desc": "Check if unauthenticated users can list/download models",
        "start_scan": "Start Scan",
        "scanning": "Scanning...",
        "scan_complete": "Scan Complete",
        "risk_score": "Risk Score",
        "findings": "Findings",
        "critical": "Critical",
        "high": "High",
        "medium": "Medium",
        "low": "Low",
        "info": "Info",
        "no_issues": "No security issues found",
        "recommendation": "Recommendation",
        "evidence": "Evidence",
        "export_html": "Export HTML Report",
        "export_pdf": "Export PDF",
        "history": "History",
        "settings": "Settings",
        "language": "Language",
        "back": "Back",
        "close": "Close",
        "port": "Port",
        "service": "Service",
        "version": "Version",
        "status": "Status",
        "open": "Open",
        "closed": "Closed",
        "filtered": "Filtered",
        "details": "Details",
        "summary": "Summary",
        "grade": "Security Grade",
        "scan_time": "Scan Time",
        "target_info": "Target Info",
        "total_ports": "Ports Scanned",
        "open_ports": "Open Ports",
        "ai_services": "AI Services",
    }
}

def t(key: str, lang: str = "zh") -> str:
    """Get translated string."""
    return I18N.get(lang, I18N["zh"]).get(key, key)
